// Mocks generated by Mockito 5.4.6 from annotations
// in vantura/test/mocks/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:convert' as _i6;
import 'dart:typed_data' as _i8;
import 'dart:ui' as _i11;

import 'package:http/http.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:vantura/core/cancellation_token.dart' as _i13;
import 'package:vantura/core/logger.dart' as _i3;
import 'package:vantura/core/vantura_client.dart' as _i4;
import 'package:vantura/core/vantura_memory.dart' as _i9;
import 'package:vantura/core/vantura_persistence.dart' as _i12;
import 'package:vantura/core/vantura_state.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeResponse_0 extends _i1.SmartFake implements _i2.Response {
  _FakeResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamedResponse_1 extends _i1.SmartFake
    implements _i2.StreamedResponse {
  _FakeStreamedResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeVanturaLogger_2 extends _i1.SmartFake implements _i3.VanturaLogger {
  _FakeVanturaLogger_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeVanturaClient_3 extends _i1.SmartFake implements _i4.VanturaClient {
  _FakeVanturaClient_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeVanturaLoggerOptions_4 extends _i1.SmartFake
    implements _i3.VanturaLoggerOptions {
  _FakeVanturaLoggerOptions_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockClient extends _i1.Mock implements _i2.Client {
  MockClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Response> head(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(
            Invocation.method(#head, [url], {#headers: headers}),
            returnValue: _i5.Future<_i2.Response>.value(
              _FakeResponse_0(
                this,
                Invocation.method(#head, [url], {#headers: headers}),
              ),
            ),
          )
          as _i5.Future<_i2.Response>);

  @override
  _i5.Future<_i2.Response> get(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(
            Invocation.method(#get, [url], {#headers: headers}),
            returnValue: _i5.Future<_i2.Response>.value(
              _FakeResponse_0(
                this,
                Invocation.method(#get, [url], {#headers: headers}),
              ),
            ),
          )
          as _i5.Future<_i2.Response>);

  @override
  _i5.Future<_i2.Response> post(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i6.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #post,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i5.Future<_i2.Response>.value(
              _FakeResponse_0(
                this,
                Invocation.method(
                  #post,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i5.Future<_i2.Response>);

  @override
  _i5.Future<_i2.Response> put(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i6.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #put,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i5.Future<_i2.Response>.value(
              _FakeResponse_0(
                this,
                Invocation.method(
                  #put,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i5.Future<_i2.Response>);

  @override
  _i5.Future<_i2.Response> patch(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i6.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #patch,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i5.Future<_i2.Response>.value(
              _FakeResponse_0(
                this,
                Invocation.method(
                  #patch,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i5.Future<_i2.Response>);

  @override
  _i5.Future<_i2.Response> delete(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i6.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i5.Future<_i2.Response>.value(
              _FakeResponse_0(
                this,
                Invocation.method(
                  #delete,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i5.Future<_i2.Response>);

  @override
  _i5.Future<String> read(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(
            Invocation.method(#read, [url], {#headers: headers}),
            returnValue: _i5.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#read, [url], {#headers: headers}),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<_i8.Uint8List> readBytes(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#readBytes, [url], {#headers: headers}),
            returnValue: _i5.Future<_i8.Uint8List>.value(_i8.Uint8List(0)),
          )
          as _i5.Future<_i8.Uint8List>);

  @override
  _i5.Future<_i2.StreamedResponse> send(_i2.BaseRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#send, [request]),
            returnValue: _i5.Future<_i2.StreamedResponse>.value(
              _FakeStreamedResponse_1(
                this,
                Invocation.method(#send, [request]),
              ),
            ),
          )
          as _i5.Future<_i2.StreamedResponse>);

  @override
  void close() => super.noSuchMethod(
    Invocation.method(#close, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [VanturaMemory].
///
/// See the documentation for Mockito's code generation for more information.
class MockVanturaMemory extends _i1.Mock implements _i9.VanturaMemory {
  MockVanturaMemory() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get shortLimit =>
      (super.noSuchMethod(Invocation.getter(#shortLimit), returnValue: 0)
          as int);

  @override
  int get longLimit =>
      (super.noSuchMethod(Invocation.getter(#longLimit), returnValue: 0)
          as int);

  @override
  _i3.VanturaLogger get logger =>
      (super.noSuchMethod(
            Invocation.getter(#logger),
            returnValue: _FakeVanturaLogger_2(this, Invocation.getter(#logger)),
          )
          as _i3.VanturaLogger);

  @override
  _i4.VanturaClient get client =>
      (super.noSuchMethod(
            Invocation.getter(#client),
            returnValue: _FakeVanturaClient_3(this, Invocation.getter(#client)),
          )
          as _i4.VanturaClient);

  @override
  _i5.Future<void> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> addMessage(
    String? role,
    String? content, {
    List<Map<String, dynamic>>? toolCalls,
    String? toolCallId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #addMessage,
              [role, content],
              {#toolCalls: toolCalls, #toolCallId: toolCallId},
            ),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  List<Map<String, dynamic>> getMessages() =>
      (super.noSuchMethod(
            Invocation.method(#getMessages, []),
            returnValue: <Map<String, dynamic>>[],
          )
          as List<Map<String, dynamic>>);

  @override
  void clear() => super.noSuchMethod(
    Invocation.method(#clear, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [VanturaState].
///
/// See the documentation for Mockito's code generation for more information.
class MockVanturaState extends _i1.Mock implements _i10.VanturaState {
  MockVanturaState() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isRunning =>
      (super.noSuchMethod(Invocation.getter(#isRunning), returnValue: false)
          as bool);

  @override
  String get currentStep =>
      (super.noSuchMethod(
            Invocation.getter(#currentStep),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#currentStep),
            ),
          )
          as String);

  @override
  set isRunning(bool? value) => super.noSuchMethod(
    Invocation.setter(#isRunning, value),
    returnValueForMissingStub: null,
  );

  @override
  set currentStep(String? value) => super.noSuchMethod(
    Invocation.setter(#currentStep, value),
    returnValueForMissingStub: null,
  );

  @override
  set errorMessage(String? value) => super.noSuchMethod(
    Invocation.setter(#errorMessage, value),
    returnValueForMissingStub: null,
  );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void startRun() => super.noSuchMethod(
    Invocation.method(#startRun, []),
    returnValueForMissingStub: null,
  );

  @override
  void updateStep(String? step) => super.noSuchMethod(
    Invocation.method(#updateStep, [step]),
    returnValueForMissingStub: null,
  );

  @override
  void completeRun() => super.noSuchMethod(
    Invocation.method(#completeRun, []),
    returnValueForMissingStub: null,
  );

  @override
  void failRun(String? error) => super.noSuchMethod(
    Invocation.method(#failRun, [error]),
    returnValueForMissingStub: null,
  );

  @override
  void reset() => super.noSuchMethod(
    Invocation.method(#reset, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i11.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i11.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [VanturaLogger].
///
/// See the documentation for Mockito's code generation for more information.
class MockVanturaLogger extends _i1.Mock implements _i3.VanturaLogger {
  MockVanturaLogger() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.VanturaLoggerOptions get options =>
      (super.noSuchMethod(
            Invocation.getter(#options),
            returnValue: _FakeVanturaLoggerOptions_4(
              this,
              Invocation.getter(#options),
            ),
          )
          as _i3.VanturaLoggerOptions);

  @override
  void debug(String? message, {String? tag, Map<String, dynamic>? extra}) =>
      super.noSuchMethod(
        Invocation.method(#debug, [message], {#tag: tag, #extra: extra}),
        returnValueForMissingStub: null,
      );

  @override
  void info(String? message, {String? tag, Map<String, dynamic>? extra}) =>
      super.noSuchMethod(
        Invocation.method(#info, [message], {#tag: tag, #extra: extra}),
        returnValueForMissingStub: null,
      );

  @override
  void warning(
    String? message, {
    String? tag,
    Map<String, dynamic>? extra,
    Object? error,
  }) => super.noSuchMethod(
    Invocation.method(
      #warning,
      [message],
      {#tag: tag, #extra: extra, #error: error},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void error(
    String? message, {
    String? tag,
    Map<String, dynamic>? extra,
    Object? error,
    StackTrace? stackTrace,
  }) => super.noSuchMethod(
    Invocation.method(
      #error,
      [message],
      {#tag: tag, #extra: extra, #error: error, #stackTrace: stackTrace},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void logPerformance(
    String? operation,
    Duration? duration, {
    Map<String, dynamic>? context,
  }) => super.noSuchMethod(
    Invocation.method(
      #logPerformance,
      [operation, duration],
      {#context: context},
    ),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [VanturaPersistence].
///
/// See the documentation for Mockito's code generation for more information.
class MockVanturaPersistence extends _i1.Mock
    implements _i12.VanturaPersistence {
  MockVanturaPersistence() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> saveMessage(
    String? role,
    String? content, {
    bool? isSummary = false,
    List<Map<String, dynamic>>? toolCalls,
    String? toolCallId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #saveMessage,
              [role, content],
              {
                #isSummary: isSummary,
                #toolCalls: toolCalls,
                #toolCallId: toolCallId,
              },
            ),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<Map<String, dynamic>>> loadMessages() =>
      (super.noSuchMethod(
            Invocation.method(#loadMessages, []),
            returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i5.Future<List<Map<String, dynamic>>>);

  @override
  _i5.Future<void> clearMessages() =>
      (super.noSuchMethod(
            Invocation.method(#clearMessages, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteOldMessages(int? limit) =>
      (super.noSuchMethod(
            Invocation.method(#deleteOldMessages, [limit]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [VanturaClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockVanturaClient extends _i1.Mock implements _i4.VanturaClient {
  MockVanturaClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get apiKey =>
      (super.noSuchMethod(
            Invocation.getter(#apiKey),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#apiKey),
            ),
          )
          as String);

  @override
  String get baseUrl =>
      (super.noSuchMethod(
            Invocation.getter(#baseUrl),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#baseUrl),
            ),
          )
          as String);

  @override
  String get model =>
      (super.noSuchMethod(
            Invocation.getter(#model),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#model),
            ),
          )
          as String);

  @override
  _i5.Future<Map<String, dynamic>> sendChatRequest(
    List<Map<String, dynamic>>? messages,
    List<Map<String, dynamic>>? tools, {
    double? temperature,
    int? maxCompletionTokens,
    double? topP,
    bool? stream,
    String? reasoningEffort,
    dynamic stop,
    _i13.CancellationToken? cancellationToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #sendChatRequest,
              [messages, tools],
              {
                #temperature: temperature,
                #maxCompletionTokens: maxCompletionTokens,
                #topP: topP,
                #stream: stream,
                #reasoningEffort: reasoningEffort,
                #stop: stop,
                #cancellationToken: cancellationToken,
              },
            ),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Stream<Map<String, dynamic>> sendStreamingChatRequest(
    List<Map<String, dynamic>>? messages,
    List<Map<String, dynamic>>? tools, {
    double? temperature,
    int? maxCompletionTokens,
    double? topP,
    String? reasoningEffort,
    dynamic stop,
    _i13.CancellationToken? cancellationToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #sendStreamingChatRequest,
              [messages, tools],
              {
                #temperature: temperature,
                #maxCompletionTokens: maxCompletionTokens,
                #topP: topP,
                #reasoningEffort: reasoningEffort,
                #stop: stop,
                #cancellationToken: cancellationToken,
              },
            ),
            returnValue: _i5.Stream<Map<String, dynamic>>.empty(),
          )
          as _i5.Stream<Map<String, dynamic>>);

  @override
  void close() => super.noSuchMethod(
    Invocation.method(#close, []),
    returnValueForMissingStub: null,
  );
}
